# 加载Keras中的MNIST数据集

In [1]:
from keras.datasets import mnist

Using TensorFlow backend.


In [2]:
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [3]:
train_images.shape  # 60000张训练图像，每张图像28*28维

(60000, 28, 28)

In [4]:
len(train_labels)

60000

In [5]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [6]:
test_images.shape

(10000, 28, 28)

In [7]:
len(test_labels)

10000

In [8]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

# 网络架构

In [9]:
from keras import models
from keras import layers

In [10]:
# 通过向Sequential模型传递一个layer的list来构造该模型

In [11]:
network = models.Sequential()

In [12]:
# 可以使用.add()方法一个一个的降layer加入模型中

In [12]:
network.add(layers.Dense(units=512, activation='relu', input_shape=(28 * 28, )))

In [13]:
network.add(layers.Dense(units=10, activation='softmax'))

# 编译步骤

In [14]:
# 想要训练网络我们还需要选择编译(compile)步骤的三个参数：损失函数(loss function)、优化器(optimizer)以及在训练测试过程中需要监控的指标(metric)

In [15]:
network.compile(loss='categorical_crossentropy', optimizer='rmsprop', metrics=['accuracy'])

# 准备图像数据

In [16]:
# 对数据进行预处理，将其变换为网络要求的形状，并将所有值缩放到[0, 1]之间

In [17]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype('float32') / 255  # astype强制转化为指定类型

In [18]:
test_images = test_images.reshape(10000, 28 * 28)
test_images = test_images.astype('float32') / 255

# 准备标签

In [19]:
# Convert labels to categorical one-hot encoding

In [20]:
from keras.utils import to_categorical

In [21]:
# 我们还需要对标签进行分类编码

In [22]:
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [23]:
test_labels

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

# 拟合模型

In [24]:
# 通过fit()方法完成训练数据的拟合

In [25]:
network.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
60000/60000 [==============================] - 5s - loss: 0.2562 - acc: 0.9253     
Epoch 2/5
60000/60000 [==============================] - 5s - loss: 0.1027 - acc: 0.9694     
Epoch 3/5
60000/60000 [==============================] - 6s - loss: 0.0682 - acc: 0.9796     
Epoch 4/5
60000/60000 [==============================] - 6s - loss: 0.0504 - acc: 0.9845     
Epoch 5/5
60000/60000 [==============================] - 6s - loss: 0.0381 - acc: 0.9884     


In [26]:
# 模型很快在训练数据上达到了98.92%的精度，现在检查一下模型在测试集上的性能

In [27]:
test_loss, test_acc = network.evaluate(test_images, test_labels)

 9344/10000 [===========================>..] - ETA: 0s

In [28]:
print('accacy:{accacy}'.format(accacy=test_acc))

accacy:0.9804


In [60]:
# 训练精度与测试精度之间的差距有点大，是因为过拟合造成的